id: 169
user: eq19
span: span-150
title: eQuantum
baseurl: /workterms
repository: ZeroWeak/workterms
action: ZeroWeak/spectral/actions/runs/37962657773
description: eQuantum Project - Zero Weak Boson

debug:
  dist: false
  compress: true
  shortcodes: true

lsi: false
incremental: true
highlighter: rouge
plugins_dir: _plugins

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

exclude:
  - LICENSE
  - vendor/
  - action.yml  
  - Dockerfile

plugins:
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
  spin: [12, 12]
  pinned: [maps, feed, lexer, parser, syntax, grammar, pysme, numqi, pyrate, nthmc, spectral, workterms]
  organization: [Chetabahana, FeedMapping, GlobalZones, HybridModels, JunctionTerms, KernelPatterns, MappingSystem, NeuralSystem, ObjectModules, VirtualNetworks, WeakNegative, WeakPositive, ZeroWeak]
